### ISSUE TITLE
[ERROR] This user does not exist .

### ISSUE THREAD

**Issue by vanshady** [liuwons/wxBot#1]
为什么我扫了二维码之后提示 This user does not exist

`[INFO] Please use WeCaht to scan QR code in qr.jpg .`
`[INFO] Please confirm to login .`
`[INFO] Web WeChat login succeed .`
`[INFO] Web WeChat init succeed .`
`[INFO] Get 448 contacts`
`[INFO] Start to process messages .`
`[ERROR] This user does not exist .`

**Comment by liuwons** [comment]
@vanshady 因为测试代码test.py里发送schedule消息的微信号tb不是你的好友，你试着把tb换成你好友的微信号试试，或者直接删掉test.py里的schedule函数

**Comment by vanshady** [comment]
OK 谢啦
