### ISSUE TITLE
获取不到用户信息了，好像微信更新了

### ISSUE THREAD

**Issue by vivre90** [liuwons/wxBot#102]
貌似有了wx2.qq.com，用户会分配到不同的域名上，我一个账号

账号获取contact旧借口：
**https://wx.qq.com**/cgi-bin/mmwebwx-bin/webwxgetcontact?pass_ticket=PMcLbyCnRlopVg%252Brchb%252BLlZKdXdAHVT7P6FBEbDOA754lfoXpNbrJ2S0SucNptwA&r=1471272315275&seq=0&skey=@crypt_6097b1dd_ed78c9fa482aafc192631462cb07572f

账号获取contact新的接口：
**https://wx2.qq.com**/cgi-bin/mmwebwx-bin/webwxgetcontact?r=1471272220798&seq=0&skey=@crypt_52c3a359_fbf93c3e99252ac5f2d2658c75ef86a2

逻辑有比较大改动！

**Comment by script74** [comment]
嗯呢，群里@无效了。。。
另外有没有即时的讨论组啊QQ微信群什么的。

**Comment by vivre90** [comment]
今天晚上10点多，又出现相同情况了，微信大姨妈了？

**Comment by zjhong** [comment]
我刚加到群里，怎么都不说话。睡了一夜醒来，就自动好了，但是新问题是，机器人在群里就和我说话，不理别人。

**Comment by liuwons** [comment]
已创建QQ交流群：429134510
