### ISSUE TITLE
基于master版本的Python3版本

### ISSUE THREAD

**Issue by 6bigfire** [liuwons/wxBot#103]
今天基于master主线版本刚调试通的，修改了wxbot.py和bot.py里已发现的和python3不兼容的所有问题。
单聊，群聊，收图片，收语音，图灵机器人，都OK。但我不知道怎么传上来

**Comment by xmcp** [comment]
先[fork](https://help.github.com/articles/fork-a-repo/)，改完之后push到自己fork的repository然后发[pull request](https://help.github.com/articles/creating-a-pull-request/)。
