### ISSUE TITLE
似乎没有对昵称中存在的表情作转义

### ISSUE THREAD

**Issue by lyyyuna** [liuwons/wxBot#11]
我看 content 你处理了 ‘<>’，似乎昵称没处理。
需要 html.unescape(nickname)

**Comment by liuwons** [comment]
@lyyyuna   好像微信不允许昵称里有'<>'

**Comment by lyyyuna** [comment]
@liuwons 有些人的昵称是表情，表现出来是这样
<span>xxxxx</span>.
传输过来是
&lt, &gt

当然群名片是不允许有表情，但昵称可以，若有人没设置群名片则会有问题。

**Comment by liuwons** [comment]
已在 `master-dev` 中 `unescape` ， 谢谢反馈 ^-^
