### ISSUE TITLE
没有qrcode？

### ISSUE THREAD

**Issue by moboard** [liuwons/wxBot#115]
pythong2.7 weixin.py提示缺少qrcode，但是提前用pip install 安装过。

pip show qrcode 
---
Metadata-Version: 2.0
Name: qrcode
Version: 5.3
Summary: QR Code image generator
Home-page: https://github.com/lincolnloop/python-qrcode
Author: Lincoln Loop
Author-email: info@lincolnloop.com
Installer: pip
License: BSD
Location: /usr/lib/python3.5/site-packages
Requires: six
Classifiers:
  Development Status :: 5 - Production/Stable
  License :: OSI Approved :: BSD License
  Operating System :: OS Independent
  Intended Audience :: Developers
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Topic :: Multimedia :: Graphics
  Topic :: Software Development :: Libraries :: Python Modules
Entry-points:
  [console_scripts]
  qr = qrcode.console_scripts:main
---------------------
> ls /usr/lib/python3.5/site-packages/qrcode       
base.py  console_scripts.py  constants.py  exceptions.py  image/  __init__.py  main.py  mecard.py  __pycache__/  speedy.py  tests/  util.py

> ls /usr/lib/python3.5/site-packages/qrcode-5.3.dist-info/                                                                     09:55:30 
DESCRIPTION.rst  entry_points.txt  INSTALLER  METADATA  metadata.json  pbr.json  RECORD  top_level.txt  WHEEL

在python3.5下有qrcode.
 /usr/lib/python2.7/是没有qrcode的，于是
 > sudo ln -s  /usr/lib/python3.5/site-packages/qrcode /usr/lib/python2.7/   
 
 再执行 python2.7 weixin.py
 Traceback (most recent call last):
  File "weixin.py", line 24, in <module>
    from requests_toolbelt.multipart.encoder import MultipartEncoder
ImportError: No module named requests_toolbelt.multipart.encoder
后面不知道怎么办了。
系统用的是archlinux+bspwm。默认的python是3.5.2.

**Comment by xmcp** [comment]
问题是没有requests_toolbelt呀，跟qrcode无关。`pip2 install requests_toolbelt`

**Comment by ldsea** [comment]
tuling123返回这个是为什么呢
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>

 
 
------------------ Original ------------------

**Comment by xmcp** [comment]
@ldsea 你给的代码并没有包含任何有用的错误信息呀……看看哪里有更详尽的错误日志
