### ISSUE TITLE
webwxgetcontact返回的联系人json现在是不是没有群组信息了

### ISSUE THREAD

**Issue by baofaguo** [liuwons/wxBot#122]
webwxgetcontact返回的联系人json现在是不是没有群组信息了

**Comment by baofaguo** [comment]
自己搞清楚了，群聊必须在通讯录中才可以

**Comment by xuyoushuai** [comment]
现在获取通讯录好像改了，如果好友过多需要调用多次，有个参数seq，第一次传0，第二次传653469746 类似这样的数字，这个数字不知道怎么生产的，不知道你知不道
