### ISSUE TITLE
登陆错误

### ISSUE THREAD

**Issue by ylot0** [liuwons/wxBot#129]
root@wlp2s0-computer:~/wxBot-master# python bot.py
Traceback (most recent call last):
  File "bot.py", line 4, in <module>
    from wxbot import *
  File "/home/wlp2s0/wxBot-master/wxbot.py", line 18, in <module>
    from requests.exceptions import ConnectionError, ReadTimeout
ImportError: cannot import name ReadTimeout

**Comment by xmcp** [comment]
`python -m pip install requests --upgrade`
如果还有问题，发一下python和requests版本号，然后reopen这个issue。

**Comment by huangguozhen** [comment]
安装@xmcp说的更新了 requests库，程序启动的时候还是报一样的错误。
python 2.7.6
requests  2.2.1

**Comment by huangguozhen** [comment]
仍然是有这个问题
requests 2.11.1
python 2.7.6

**Comment by huangguozhen** [comment]
是本地repuests库问题，显示版本2.11.1，查看库代码还是2.2.1的。手动删除后重新安装解决问题。
