### ISSUE TITLE
登录后 sync_check() 返回的 retcode 还是 1100 .

### ISSUE THREAD

**Issue by jackey** [liuwons/wxBot#130]
启动的日志大概这样子:

[INFO] Please use WeChat to scan the QR code .
[INFO] Please confirm to login .
[INFO] Web WeChat login succeed .
[INFO] Web WeChat init succeed .
[INFO] Get 0 contacts
[INFO] Start to process messages .
proc_msg
[DEBUG] sync_check: 1100 0

直接登录网页且没有问题. 
有谁碰到过吗？

**Comment by kzx1025** [comment]
我也碰到了，你解决了吗

**Comment by dklkt** [comment]
这个问题我是最近两天才碰到的，有时是1100 0，有时是1102 0。登录官方的微信网页版没有问题。

**Comment by liuwons** [comment]
@kzx1025 @dklkt @jackey 更新到最新版有这个问题吗

**Comment by ttcn2k** [comment]
更新了最新提交了解决了问题

-        url = 'https://' + self.sync_host + '.weixin.qq.com/cgi-bin/mmwebwx-bin/synccheck?' + urllib.urlencode(params)
+        url = 'https://' + self.sync_host + '.wx.qq.com/cgi-bin/mmwebwx-bin/synccheck?' + urllib.urlencode(params)

**Comment by kzx1025** [comment]
@ttcn2k  very good!

**Comment by jackey** [comment]
@ttcn2k  感谢!
