### ISSUE TITLE
启动出现的提示

### ISSUE THREAD

**Issue by ylot0** [liuwons/wxBot#132]
系统：ubuntu14.04LTS
python:python2.7.6

root@wlp2s0-computer:~/wxBot-master# python bot.py
tuling_key: 9765cc2e6f794a03a316ad535e734aaf
[INFO] Please use WeChat to scan the QR code .

(gthumb:2910): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[ERROR] WeChat login timeout. retry in 1 secs later...
[ERROR] WeChat login timeout. retry in 1 secs later...
[ERROR] WeChat login timeout. retry in 1 secs later...
[ERROR] WeChat login timeout. retry in 1 secs later...
[INFO] Please confirm to login .
[INFO] Web WeChat login succeed .
[INFO] Web WeChat init succeed .
[INFO] Get 225 contacts
[INFO] Start to process messages .

(gthumb:2910): GLib-CRITICAL **: Source ID 160 was not found when attempting to remove it

**Comment by ylot0** [comment]
这个原因已找到，机器人在抓取到朋友圈的自定义图片后产生的问题。可能与我的二维码不是终端打开的有关系。

**Comment by shiqwang** [comment]
可以抓取朋友圈吗
