### ISSUE TITLE
wxBot在ubuntu下的各问题汇总

### ISSUE THREAD

**Issue by ylot0** [liuwons/wxBot#133]
系统：ubuntu14.04LTS
python版本：python2.7.6

问题描述：   在终端切换到root权限，使用python wxbot.py启动机器人无法启动，且没有任何提示。

使用python bot.py可以启动机器人，
问题一：二维码并未在终端显示，而是弹出图片管理器后出现二维码，扫码后有报错，

问题二：无法识别朋友的自定义图片，声音，且无回复。

问题三：抓取到图片后，声音等文件后统一集中在temp文件夹下，集中显示在图片查看器，会造成下次扫描失败。

见报错代码。
root@wlp2s0-computer:~/wxBot-master# ls
bot.py   CHANGES.md  conf.ini~  __init__.py  README.md  test.py   wxbot.pyc
bot.py~  conf.ini    img        LICENSE      temp       wxbot.py
root@wlp2s0-computer:~/wxBot-master# cd temp
root@wlp2s0-computer:~/wxBot-master/temp# rm -rf *
root@wlp2s0-computer:~/wxBot-master/temp# ls
root@wlp2s0-computer:~/wxBot-master/temp# cd ..
#注意这条命令，执行后无任何动作root@wlp2s0-computer:~/wxBot-master# python wxbot.py#注意这条命令，执行后无任何动作。
root@wlp2s0-computer:~/wxBot-master# python bot.py
tuling_key: 9765cc2e6f794a03a316ad535e734aaf
[INFO] Please use WeChat to scan the QR code .

#报错的代码(gthumb:5620): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files#报错的代码

[INFO] Please confirm to login .
[INFO] Web WeChat login succeed .
[INFO] Web WeChat init succeed .
[INFO] Get 225 contacts
[INFO] Start to process messages .

**Comment by xmcp** [comment]
- 关于“wxbot无法启动”：

`wxbot.py`是一个库，直接运行本来就**不应该有任何现象**，不信你在windows上双击运行也会直接退出。所以这不是一个bug，你应该自己写一个程序然后 `import wxbot`。

- 关于二维码没有在终端显示

根据README的描述，要想使用此功能，你需要设置`conf['qr']`为`tty`。所以这仍然不是一个bug。

- 关于`GDBus.Error`异常

这应该是`pillow`(`PIL`)显示图片时出现的异常，可能与你GNOME的配置比较奇特有关。

而且这只是Warning，所以不用管 ┑(￣Д ￣)┍

- 关于问题二和问题三

> 问题二：无法识别朋友的自定义图片，声音，且无回复。

> 问题三：抓取到图片后，声音等文件后统一集中在temp文件夹下，集中显示在图片查看器，会造成下次扫描失败。

看不懂，希望具体指明问题。

**Comment by ylot0** [comment]
感谢回复。
详述意思如下：
问题二：无法识别朋友发来的自定义图片，声音，且机器人也无回复。
意思就是：朋友如果给你发个图片，机器人是无法识别的，也不会回复。

问题三：朋友发来自定义图片后，机器人抓取到图片，会存储在wxBot目录中的temp目录中，然后都自动跑到图片查看器里去了（因为生成的二维码自动由图片查看器打开的，这个窗口一直不能关，关了会报错。），会造成下次扫描失败。

**Comment by xmcp** [comment]
- 问题二

根据现在`bot.py`的内容，处理新消息的代码都包裹在`msg['content']['type'] == 0`的if里了，所以非文字消息会被忽略。所以这不是bug，如果想处理其他类型的消息需要自己写相关代码。

- 问题三

现在`master`和`master-dev`分支的代码在非macOS平台都是通过浏览器打开二维码的呀，并不知道为什么会打开图片查看器。根据pillow相关的异常，我认为你wxbot的版本可能不是最新的，因为最新的代码已经不依赖`pillow`了。
