### ISSUE TITLE
Linux终端如何显示图片

### ISSUE THREAD

**Issue by weaming** [liuwons/wxBot#14]
Linux终端如何显示图片

**Comment by liuwons** [comment]
@weaming    显示什么图片？二维码还是图片消息？二维码的话直接在terminal里打印，消息图片的话是以url的形式提供给用户的，用户自己下载处理。

**Comment by weaming** [comment]
@liuwons 二维码打印不出来。

- 希望增加功能：保存上次session相关数据，出错时手动启动时能先尝试上次会话的信息，避免再次登录。可增加时间间隔作一个预判。
- Bug：经常出现Nonetype之类的错误，或者卡死情况，不一定是网速不好。

**Comment by liuwons** [comment]
@weaming 你用的哪个发行版的Linux，用的什么terminal？
 - 出错后再次扫码登录是必须，因为服务器端已经判定为下线了
 - NoneType的错误的确挺多，慢慢排查。卡死是sync时卡在POST请求那了，我在不同环境下测了感觉还是网络的原因。

**Comment by weaming** [comment]
VPS cenos 6.6 

```
/usr/bin/xdg-open: line 402: htmlview: command not found
/usr/bin/xdg-open: line 402: firefox: command not found
/usr/bin/xdg-open: line 402: mozilla: command not found
/usr/bin/xdg-open: line 402: netscape: command not found
/usr/bin/xdg-open: line 402: links: command not found
/usr/bin/xdg-open: line 402: lynx: command not found
xdg-open: no method available for opening 'qr.png'
```

就是那种因为卡住什么的必须重启的时候，或者出错然后重启的时候，这样也算下线？

**Comment by liuwons** [comment]
@weaming VPS上没有GUI环境所以打不开png图片？可以将VPS上的图片下载到本地打开扫描么。

卡住太长时间之后服务器端会因为长时间没有交互而判定客户端已下线。
出错后重启可以考虑利用上次保存的session，后面可以添加此功能。

**Comment by weaming** [comment]
哈哈 麻烦。
