### ISSUE TITLE
出现1102 同样问题

### ISSUE THREAD

**Issue by sixian67** [liuwons/wxBot#140]
[DEBUG] sync_check: 1102 0
send_code: 404

**Comment by lroolle** [comment]
1102 是指?

**Comment by sixian67** [comment]
哈，之前有同学有出现过那个问题，同步消息报那个错误码

**Comment by lroolle** [comment]
@sixian67 我是说 1102 问题在哪? 我现在也出现这个code 了, 之前挂了很长一段时间(5天以上). 难道是挂的时间太长?

**Comment by sixian67** [comment]
应该不是吧，换了几个号都是一样的，

**Comment by sixian67** [comment]
好像是 这两天才出现这个问题的，可能是同步消息接口变了~

**Comment by sixian67** [comment]
@lroolle 换了几个号都一样

**Comment by lroolle** [comment]
@sixian67 之前类似情况是怎么解决的？

**Comment by lroolle** [comment]
@sixian67 更新下sync host 和 接口，目前可以用了

**Comment by sixian67** [comment]
@lroolle  
嗯嗯 好的

**Comment by sixian67** [comment]
[1102问题 ] (https://github.com/liuwons/wxBot/pull/141)

**Comment by 757350134** [comment]
1102 挂两三天就出现了，求解决啊！

**Comment by xmcp** [comment]
duplicate of #120
