### ISSUE TITLE
send_img_msg_by_uid发送图片功能无法使用

### ISSUE THREAD

**Issue by Elfsong** [liuwons/wxBot#146]
`(MaxRetryError("HTTPSConnectionPool(host='file2.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1180730>: Failed to establish a new connection: [Errno 111] Connection refused',))",), 'Traceback (most recent call last):\n  File "/home/pi/wxBot/wxbot.py", line 52, in request\n    allow_redirects, proxies, hooks, stream, verify, cert, json)\n  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send\n    raise ConnectionError(e, request=request)\nConnectionError: HTTPSConnectionPool(host=\'file2.wx2.qq.com\', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by NewConnectionError(\'<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1180730>: Failed to establish a new connection: [Errno 111] Connection refused\',))\n')
`
我的python版本是2.7.3，操作系统是Debian。然后发送图片的这个函数始终报错，根据情况来看是ssl的问题。请问如何解决这个问题呢？

**Comment by vivre90** [comment]
部分地区上传图片的接口不是file2.wx2.qq.com 所以报错。

建议通过浏览器尝试上传一次图片获取上传接口的域名，修改后在使用

**Comment by Elfsong** [comment]
感谢@vivre90 按照你的方法成功了.
我这里上传的接口是file.wx.qq.com和file2.wx.qq.com
