### ISSUE TITLE
Mac os x 终端启动运行，无法正常加载用户昵称

### ISSUE THREAD

**Issue by zzvv** [liuwons/wxBot#15]
> Python -V 
  Python 2.7.11
  uname -a 
  Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015

  错误信息：
 
![jietu-16-03-06](https://cloud.githubusercontent.com/assets/11956161/13554757/9ba7afec-e3eb-11e5-88c3-69ea57b1811e.jpg)

**Comment by liuwons** [comment]
@zzvv 现在master-dev分支的代码还存在这个问题吗？

**Comment by tomsean** [comment]
@liuwons  master-dev分支的代码 对方是好友的情况下名称显示正常，但是如果是群聊天的话显示unknown

**Comment by VitoYane** [comment]
我也遇到了这个问题, 非好友不显示昵称
