### ISSUE TITLE
请问如何获取群聊里面发送消息的人？

### ISSUE THREAD

**Issue by niwanmao** [liuwons/wxBot#155]
看示例代码，收到群聊消息后，user字段对应的是群聊名称，不知道群聊里面发送消息的人如何获取？谢谢！

**Comment by CrytisMT** [comment]
同问  有没有唯一标识

**Comment by gfwfail** [comment]
同样。。获取不到。。

**Comment by yangpeiyong** [comment]
def handle_msg_all(self, msg)

user = msg['content']['user']
user['id] #用户ID
user['name'] #用户name

**Comment by jinmingshao** [comment]
对于群信息，我使用msg['content']['user']['name']来获取人名，但是全部都是unknown，只有在我通讯录里的人才能正确显示名字。请问如何解决这个问题？

**Comment by yangpeiyong** [comment]
@jinmingshao   先把群保存到通讯录里面，再次扫码登录就可以了

**Comment by jinmingshao** [comment]
对，可以看到了。谢谢！
