### ISSUE TITLE
可以通过MsgType为51的消息获取wxid，但问题是如何用web版触发51信息

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [liuwons/wxBot#162]
目前观察到的MsgType为51，并且StatusNotifyCode in [2, 4]的消息里，能获取username和wxid的对应。

但问题是web上目前没有观察到可以主动触发51信息的方式。

在手机上任意点开一个聊天，就能触发51信息，但在web上点开任何聊天都无效。

**Comment by xmcp** [comment]
那就是web微信本来就不行呗
