### ISSUE TITLE
题主有开启多个用户(线程)的思路吗

### ISSUE THREAD

**Issue by SuperXiaoxiong** [liuwons/wxBot#187]
我如果开启两个线程，第二个用户扫描二维码并登陆，微信就会返回1102，过一会返回1100

**Comment by xuncl** [comment]
更新到最新版本了吗？

**Comment by SuperXiaoxiong** [comment]
oh，谢谢，发现问题了，我是自己写的，用的urllib2 的cookie模块， 现在重写改写为requests.谢谢，题主的代码，思路清晰。
