### ISSUE TITLE
如何指定时间发送消息

### ISSUE THREAD

**Issue by hutzerg** [liuwons/wxBot#192]
例如：每日中午12点整发送推文。

**Comment by NHibiki** [comment]
python下新建thread监控时间，到时间就bot.send_msg_by_uid

**Comment by qnmlgdsb** [comment]
crontab 0 12 * * * python  xxx.py
这样应该也可以

**Comment by NHibiki** [comment]
@qnmlgdsb 噗 那你这样要分开写py，麻烦了很多呐
