### ISSUE TITLE
mac ox 运行test.py 无法看到弹出的二维码登录，但后台有log出现

### ISSUE THREAD

**Issue by cuikangyuan** [liuwons/wxBot#20]
log如下：
INFO] Please use WeCaht to scan the QR code .
[ERROR] WeChat login timeout .
[INFO] Please confirm to login .
[ERROR] WeChat login timeout .
[ERROR] Login failed due to network problem, please try again.
[ERROR] Web WeChat login failed .

是否是我的操作不正确吗？

**Comment by liuwons** [comment]
运行的文件夹下面有 `qr.png` 二维码图片文件吗？

**Comment by cuikangyuan** [comment]
恩，是有文件生成，可以运行，另外请问 脚本有执行时长限制吗，还是由于web微信有登录时长限制？昨晚睡觉前我运行脚本，正常登录，早上起床发现 脚本停止执行了，是因为 web微信长时间不操作自动退出吗？

**Comment by liuwons** [comment]
原因还没排查清楚~

**Comment by cuikangyuan** [comment]
喔喔 好的

**Comment by YixuanFranco** [comment]
@cuikangyuan 我这个也这样, 不过你可以按照 README 里面所说的,   
把 conf['qr'] 设置为 tty. 即可在终端显示二维码.

**Comment by cuikangyuan** [comment]
好的
