### ISSUE TITLE
请问wxbot群发消息时候怎么@群里的指定成员

### ISSUE THREAD

**Issue by StacieR** [liuwons/wxBot#207]
我写的
self.send_msg_by_uid(self.__proc_GroupTextMsg(msg), '@' + uid)
self.send_msg('@' + uname, self.__proc_GroupTextMsg(msg))
但是根本不能发消息出去

**Comment by mushroomlb** [comment]
是空格的问题，在@名称 后面有一个空格u'\2005'，但是一直没有成功

**Comment by StacieR** [comment]
reply = '@' + uname + u'\2005'  是这样写么

**Comment by quanpower** [comment]
不是简单加个空格就可以的，这个@在微信里面是触发了个动作，web微信暂时无解

**Comment by StacieR** [comment]
好吧，谢谢各位了

**Comment by xmcp** [comment]
duplicate of #193

**Comment by gclsoft** [comment]
@StacieR @quanpower 到底支不支持@, 我看别的群的机器人都会@我
