### ISSUE TITLE
sync_check() 返回的retcode值为1100，程序自动退出。

### ISSUE THREAD

**Issue by lyn240690234** [liuwons/wxBot#21]
微信登录后，程序能够进入proc_msg()。但是第一次运行syn_check()后，retcode为1100，程序跳出循环结束。[windows7, python2.7.10, requests 2.9.1]

![image](https://cloud.githubusercontent.com/assets/3888469/13625011/56b4d72a-e5ee-11e5-8bfe-40fef6bfefe8.png)

**Comment by liuwons** [comment]
`1100` 是手机微信退出登录的意思，是不是你从手机微信登出了？

**Comment by lyn240690234** [comment]
并没有，登录之后什么都没有做。
