### ISSUE TITLE
在Mac上运行时出了问题

### ISSUE THREAD

**Issue by Rasherpy** [liuwons/wxBot#218]
原来的工程在Windows上面还可以运行，但是到了Mac上面，用Pycharm跑，总是出现报错。在Python Interpreter里设置了python 2.7 但是报错的时候显示的是2.6.而且所需要的库文件都已经pip安装了，却还是提示没有安装

**Comment by xmcp** [comment]
这应该是你环境的问题，和wxbot无关。
另外你说没有安装库但连traceback都不给是什么鬼呀。
