### ISSUE TITLE
无法在（谷歌云虚拟机）pip安装？如何破？

### ISSUE THREAD

**Issue by telescopeuser** [liuwons/wxBot#220]
Python 2.7.10 (default, Apr  5 2017, 12:57:23)
[GCC 4.9.x 20150123 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

Command in Jupyter Notebook:
!pip install -U requests
!pip install -U pyqrcode
!pip install -U pypng
!pip install -U Pillow
!pip install -U wxbot

Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pyqrcode in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pypng in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow)
Collecting wxbot
  Could not find a version that satisfies the requirement wxbot (from versions: )
No matching distribution found for wxbot

**Comment by xmcp** [comment]
wxbot不在pypi上，没法用pip安装。所以没法破。

**Comment by telescopeuser** [comment]
那请问怎么安装啊？谢谢！

**Comment by telescopeuser** [comment]
噢哈哈，我看明白些了。这个是.py文件。可以直接运行。
谢谢！就是说要改动功能的话要进入.py文件改吧。谢谢了。

**Comment by telescopeuser** [comment]
噢哈哈，我看明白些了。这个是.py文件。可以直接运行。
谢谢！就是说要改动功能的话要进入.py文件改吧。谢谢了。
