### ISSUE TITLE
建议添加一个GUI界面，能够实时显示不同人的聊天信息。

### ISSUE THREAD

**Issue by jiawenhao2015** [liuwons/wxBot#223]
感觉将所有人的消息都放到一个控制台上输出好凌乱。来消息的时候，不同的联系人对应不同的会话窗口感觉会好很多，就像微信网页版原来那样子。
或者干脆就显示微信网页版，然后处理消息的时候经过wxBot这一层。

**Comment by xmcp** [comment]
wxbot是一个库，你所谓的“输出到控制台”只是调试用的log，并非让你去盯着看的。所以你需要在自己的程序里处理界面之类的东西。
