### ISSUE TITLE
程序运行一下就直接自动退出了.

### ISSUE THREAD

**Issue by YixuanFranco** [liuwons/wxBot#23]
'''
[INFO] Please use WeCaht to scan the QR code .
[INFO] Please confirm to login .
[INFO] Web WeChat login succeed .
[INFO] Web WeChat init succeed .
[INFO] Get 1333 contacts
[INFO] Start to process messages .
**21:27 Yixuan@Yixuans-MacBook-Pro /Users/Yixuan/Desktop/wxBot**
'''

我的系统是Mac OS X 10.11.1. 所有的依赖包都确定安装无误.  
Test 了项目中的 Python 文件,  
发现, `wxbot.py ` 无反应.  
`test.py ` 成功, 显示代码如上, 但会直接退出.
`bot.py` 已经去图灵申请了 key, 并新建了 conf.ini 文件, 放入 Key, 测试结果同上. 有反应. 也会显示联系人, 但说完 start to process messages 就直接退出了.  

还有第一行的 " Please use WeCaht to scan the QR code ."  
WeChat 拼写错误.

**Comment by YixuanFranco** [comment]
拼写错误已经发了 push request, 改正过来了, 劳烦merge 下.

**Comment by liuwons** [comment]
已merge，另外你能debug出具体是在哪一行退出的吗，控制台消息看不出是什么原因退出的(ಥ _ ಥ)

**Comment by YixuanFranco** [comment]
T_T 不知道... test.py 只改动了 tty, 然后schedule 那个我还是注释呢, 所以不存在 什么tb 用户的问题...
别的真的是一点都木有改. 到底是哪里出错我也不知道...

**Comment by YixuanFranco** [comment]
T_T 不知道... test.py 只改动了 tty, 然后schedule 那个我还是注释呢, 所以不存在 什么tb 用户的问题...
别的真的是一点都木有改. 到底是哪里出错我也不知道...

**Comment by lixuda** [comment]
过一段时间后，掉线了，无法接受信息了

**Comment by chaonet** [comment]
@YixuanFranco 可能是`wxbot.py`模块里`proc_msg`这个类方法意外退出了，试试在`while`主循环 和 几个`if`语句下面放`print`语句，看看语句执行情况，然后打印变量值试试

**Comment by lixuda** [comment]
@chaonet  程序当没有退出或者提示错误，代码还没有仔细看，一开始运行正常，可能几分钟后，程序还在运行，无法接受到微信的信息。win7 py27

**Comment by liuwons** [comment]
如果新版本还有次问题请重开此issue

**Comment by YixuanFranco** [comment]
@chaonet 我这里也没有错误提示. 在 start to process message  后迅速退出了. 
fork 的是新版本.

**Comment by YixuanFranco** [comment]
'''
        self.get_contact()
        print '[INFO] Get %d contacts' % len(self.contact_list)
        print '[INFO] Start to process messages .'
        self.proc_msg()
'''

@liuwons  前面都明显运行没问题, 目测应该是....`wxbot.py` 中的 `  self.proc_msg()`模块, 不知什么原因被 pass 了? 因为没有报错哎.

**Comment by wenzhoou** [comment]
self.proc_msg() 中接收到信息为 1100，0 所以退出了。什么原因呢？

**Comment by wenzhoou** [comment]
已经证实要改这句话
        for host in ['webpush.weixin.qq', 'webpush2.weixin.qq', 'webpush.wechat', 'webpush1.wechat', 'webpush2.wechat', 'webpush.wechatapp', 'webpush1.wechatapp']:
