### ISSUE TITLE
自己改造了下，能作为微信支付免签接口使用

### ISSUE THREAD

**Issue by leoleoasd** [liuwons/wxBot#241]
rt，改造了xml解析的方式，就能作为微信支付接口使用了

**Comment by xmcp** [comment]
这种事不是应该发PR吗？发issue是啥意思

**Comment by fsdos** [comment]
支付宝、微信个人免签支付接口是个系统工程，需要手机端APP、后端程序的相互配合才能完成。
整个系统分成两部分：

1、手机端APP调用支付宝、微信生成收款码，在收款码中自动设置订单号为备注，并返回收款二维码URL给接口
2、支付成功后，手机端APP捕捉到支付成功信号，并异步回调给指定接口。


个人支付宝免签接口,微信支付免签,1分钱测试地址： 

http://shop.fteftk.com/paydemo/admin/order_public.php


用个人收款码收款,使用订单号作为备注，支付成功后向指定地址发送异步回调消息
