### ISSUE TITLE
SSL 证书验证失败 大家是怎么解决这个问题的

### ISSUE THREAD

**Issue by TenaciousZ** [liuwons/wxBot#257]
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by xmcp** [comment]
#150

**Comment by francisoliverlee** [comment]
![image](https://user-images.githubusercontent.com/5908412/27995834-d3fdc2ac-6507-11e7-9146-8e8274d3669b.png)
