### ISSUE TITLE
码主，{retcode:"0",selector:"6"}等于6是什么意思？

### ISSUE THREAD

**Issue by zacard-orc** [liuwons/wxBot#26]
window.synccheck={retcode:"0",selector:"0"}

**Comment by liuwons** [comment]
我也不知道，暂时没遇到过等于6的情况。
微信官方没有文档，所以这些 `code` 的含义都是通过 找资料+实测 获取的。

**Comment by zacard-orc** [comment]
我这里，一般跑了1小时后会出现selector 6的情况，这是日志。有没有可能重新拿KEY，再救回来？
20160314 22:30:33 connectionpool.py[line:242] INFO <_get_conn> Resetting dropped connection: webpush.weixin.qq.com
20160314 22:30:33 connectionpool.py[line:387] DEBUG <_make_request> "GET /cgi-bin/mmwebwx-bin/synccheck?synckey=1_640195217%7C2_640195710%7C3_640195612%7C11_640195598%7C13_640160066%7C201_1457962834%7C1000_1457950933&skey=%40crypt_7edd960c_0345379407777b970287434fb1a86076&uin=2082299604&r=1457965833&deviceid=e978319405479423&sid=KRbYEyWmv6fqHGF5&_=1457965833 HTTP/1.1" 200 43
20160314 22:30:33 wxbot.py[line:1063] INFO <sync_check> window.synccheck={retcode:"0",selector:"6"}

**Comment by liuwons** [comment]
重新拿 `key` 还要重新扫描二维码吧。
你这是哪个版本的，我在 `master` 最新的版本里加了 `timeout`， 还会有这种情况吗。

**Comment by zacard-orc** [comment]
上周clone的版本，今早上现在在proc_msg中加了段，
  elif selector == '4':  # ??? unknown maybe to fast
                    r = self.sync()
                    if r is not None:
                        self.handle_msg(r)
                    self.OpsOutMessage(6,'wxbot synccheck selector 4')
                elif selector == '6':  # ??? unknown maybe to fast
                    r = self.sync()
                    if r is not None:
                        self.handle_msg(r)
                    self.OpsOutMessage(6,'wxbot synccheck selector 6')
目前观察下来，key的同步都还算正常.
另外，你说的超时是不是这段？
#check_time = time.time() - check_time
            time.sleep(3)
            #if check_time < 5:
            #    time.sleep(0.5 - check_time)
我自己重试了下，延迟个几面问题都不大。

**Comment by liuwons** [comment]
没看明白你的意思。是遇到了 `selector` 等于4和6的情况吗。
**超时**：我在发送的 **HTTP** **POST**  以及 **GET** 请求上设置了超时时间。

**Comment by zacard-orc** [comment]
OK
