### ISSUE TITLE
运行bot.py,发送"你好",出现UnicodeEncodeError

### ISSUE THREAD

**Issue by mContext** [liuwons/wxBot#279]
[INFO] Please use WeChat to scan the QR code .
[INFO] Please confirm to login .
[INFO] Web WeChat login succeed .
[INFO] Web WeChat init succeed .
[INFO] Get 186 contacts
[INFO] Start to process messages .
[ERROR] Except in proc_msg
Traceback (most recent call last):
  File "/home/wxBot-master/wxbot.py", line 786, in proc_msg
    self.handle_msg(r)
  File "/home/wxBot-master/wxbot.py", line 752, in handle_msg
    print u'[MSG] %s:' % user['name']
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-9: ordinal not in range(128)

**Comment by mContext** [comment]
不是打印,是尝试发消息的时候,没法出去,直接报错

**Comment by fourierrr** [comment]
微信接口改了，发不了了，只能向文件助手发，其他的都发送不了了。
