### ISSUE TITLE
mtype==47,原创表情符容错

### ISSUE THREAD

**Issue by zacard-orc** [liuwons/wxBot#29]
mtype==47,原创表情符虽命中Animation，但微信给的message content为空导致后面self.search_content('cdnurl', content),schema被带入unknown，继而main crash，此处需要容错。

**Comment by liuwons** [comment]
嗯，有时间我调试下~

**Comment by liuwons** [comment]
@zacard-orc 没重现crash，你试试当前版本是否还有这个问题？有的话 reopen issue ~ ![后台](https://cloud.githubusercontent.com/assets/9864950/14602569/3b88c7aa-059b-11e6-9900-f374ed6ce416.png)
