### ISSUE TITLE
如何获取群聊中成员的头像？

### ISSUE THREAD

**Issue by xmcp** [liuwons/wxBot#30]
`WXBot.group_members`里面没有用户头像的URL，如果直接去把`group_members`里面的`UserName`扔进`WXBot.get_icon`方法的话有很大比例加载不了头像（HTTP状态码是200，但是响应正文长度是0）。

观察了一下微信网页版的群聊界面，发现头像的URL后面有一个`chatroomid`参数，但是不知道怎么获取。

**Comment by liuwons** [comment]
暂时还没分析这个协议。

**Comment by liuwons** [comment]
@xmcp 已添加获取群聊成员头像功能。
使用方法： 调用函数```get_icon(self, uid, gid=None)```时设置对应的群id(```gid```)以及成员id(```uid```)
