### ISSUE TITLE
如何对指定的群发送消息？

### ISSUE THREAD

**Issue by foxaunt** [liuwons/wxBot#34]
send_msg 或 send_msg_by_uid 能否对指定的群发送消息？ 有没有实现的办法？

**Comment by molog** [comment]
@foxaunt 需要获取群的id，然后send_msg_by_uid(msg, group_id) 就可以了
现在版本里获取group_list的方法失灵了。我观察了下，似乎在init的时候可以获取一个群会话列表。
也可以在群里主动发一个消息，然后获取到group_id。group_id是@@开头的

**Comment by liuwons** [comment]
@molog @foxaunt  ```group_list``` 列表里应该含有已保存的所有群，获取群id(```UserName```)后```send_msg_by_uid```就可以了。
