### ISSUE TITLE
登录成功初始化失败

### ISSUE THREAD

**Issue by zyx870805** [liuwons/wxBot#35]
初始化的地址是：https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxinit?r=1458554541&lang=en_US&pass_ticket=jpjBfpQ%2BhSB1I7MFQWs29AJCKNUQBQnGTXTVSsl%2BvoLGddrngaxPSHEeB5d%2BAn5H

请求参数如下：
"BaseRequest" -> "{"DeviceID":"e928816667635154","Uin":"2051992284","Skey":"@crypt_a626cc56_f9e3769fd62f6d2221de3348d5803836","Sid":"DB1J8QJiR+DmVJVh"}"

返回信息如下：
{"BaseResponse": {"Ret": 1,"ErrMsg": ""},"Count": 0,"ContactList": [],"SyncKey": {"Count": 0,"List": []},"User": {"Uin": 0,"UserName": "","NickName": "","HeadImgUrl": "","RemarkName": "","PYInitial": "","PYQuanPin": "","RemarkPYInitial": "","RemarkPYQuanPin": "","HideInputBarFlag": 0,"StarFriend": 0,"Sex": 0,"Signature": "","AppAccountFlag": 0,"VerifyFlag": 0,"ContactFlag": 0,"WebWxPluginSwitch": 0,"HeadImgFlag": 0,"SnsFlag": 0},"ChatSet": "","SKey": "","ClientVersion": 0,"SystemTime": 0,"GrayScale": 0,"InviteStartCount": 0,"MPSubscribeMsgCount": 0,"MPSubscribeMsgList": [],"ClickReportInterval": 0}

初始化失败，请问是什么原因呢， 是我post请求的原因吗？

**Comment by liuwons** [comment]
@zyx870805 请问是每次初始化都会失败吗？
