### ISSUE TITLE
经常卡死的问题

### ISSUE THREAD

**Issue by songkaiape** [liuwons/wxBot#37]
我使用一段时间感觉经常会出现卡死，我觉得可能是因为图灵机器人发了一些无法处理的东西，比如之间问他天气，就会导致程序卡住，代码里面是不是没有处理这方面的信息所以导致程序卡死了

**Comment by liyunxing** [comment]
我也遇到这种情况了，感觉是一段时间不用，链接就断开了

**Comment by liuwons** [comment]
如果新版本还有此问题请重开此issue
