### ISSUE TITLE
run test.py有问题

### ISSUE THREAD

**Issue by lxj0276** [liuwons/wxBot#41]
出现这个错误，是怎么回事requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by liuwons** [comment]
**Requests** 是哪个版本的？试试更新下 **Requests** 版本？

**Comment by lxj0276** [comment]
我的Requests 是2.9.1，python是2.7.10，找不到原因啊

**Comment by liuwons** [comment]
[python-requests-throwing-up-sslerror](http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror) 试试这个链接里的方法？

**Comment by francisoliverlee** [comment]
https://github.com/liuwons/wxBot/issues/257
