### ISSUE TITLE
发送图片和语音问题

### ISSUE THREAD

**Issue by liyunxing** [liuwons/wxBot#42]
文档说支持图片和语音，我修改了下代码测试发现，发出来的是url；
后来修改了
#            msg_content['data'] = self.get_voice_url(msg_id)
            msg_content['data'] = self.get_voice(msg_id)
还是不行

**Comment by zhijing83** [comment]
图片我能发送，语音，名片链接等还没弄清楚，有明白的不？

**Comment by Yad2206** [comment]
@zhijing83 图片是怎么发送的呢？ 文本能发送，图片和语音发送不了，只能看到图片和语音被下载到本地

**Comment by zhijing83** [comment]
图片要upload再send

**Comment by liuwons** [comment]
目前支持机器人接收图片和语音(会下载到本地文件)，但不支持机器人发送图片和语音。
例如接受到语音后：

![后台接收语音](https://cloud.githubusercontent.com/assets/9864950/14602229/5f2f3056-0599-11e6-94da-002368b59bb4.png)


![语音文件](https://cloud.githubusercontent.com/assets/9864950/14602189/31cef0c4-0599-11e6-93e8-d4b6940371ac.png)
