### ISSUE TITLE
test.py问题

### ISSUE THREAD

**Issue by xu-xiang** [liuwons/wxBot#46]
还是test.py中   修改用户tb为 我的好友名称后报错如下

[INFO] Please use WeChat to scan the QR code .
[INFO] Web WeChat login succeed .
[INFO] Web WeChat init succeed .
[INFO] Get 176 contacts
[INFO] Start to process messages .
/git/my/wxBot-master-dev/wxbot.py:644: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if 'RemarkName' in contact and contact['RemarkName'] == name:
/git/my/wxBot-master-dev/wxbot.py:646: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif 'NickName' in contact and contact['NickName'] == name:
/git/my/wxBot-master-dev/wxbot.py:648: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif 'DisplayName' in contact and contact['DisplayName'] == name:
[ERROR] This user does not exist .
[ERROR] This user does not exist .

**Comment by xu-xiang** [comment]
发现还是由于对中文的不支持导致的，查看  contact_list.json 对象 ，发现"RemarkName": "\u91d1\u9756\u4eba"，应该这边编码要修改下才行

**Comment by liuwons** [comment]
修改用户名时，如果是非英文，请用 **unicode** 字符串，例如```self.send_msg(u'张三', u'测试')```
