### ISSUE TITLE
发送语音消息

### ISSUE THREAD

**Issue by chenJz1012** [liuwons/wxBot#48]
想实现发送语音消息功能，或者转发语音，请问有相关接口吗？

**Comment by hujiaogen** [comment]
还有发送和转发图片的接口也是找不到

**Comment by liuwons** [comment]
@chenJz1012 本项目是利用Web微信的接口实现的，而Web微信是不支持发送语音的，因此 **wxBot** 没有发送语音的接口。

**Comment by chenJz1012** [comment]
谢谢~
