### ISSUE TITLE
用 2to3.py转master的wxbot.py 出现奇怪的问题

### ISSUE THREAD

**Issue by ixiusama** [liuwons/wxBot#52]
```
    f.write(r.text.encode('utf-8'))
TypeError: write() argument must be str, not bytes
```

弹出这个。。。这不就是已经是用 .encode 转过的 `str` 了吗？

**Comment by xmcp** [comment]
是啊

**Comment by ixiusama** [comment]
咦，那怎么办？（手动斜眼

**Comment by xmcp** [comment]
别encode了啊

**Comment by ixiusama** [comment]
去除 encode 报错
`UnicodeEncodeError: 'gbk' codec can't encode character '\u2006' in position 43797: illegal multibyte sequence`
更新最新版（4/28）后报错一样。
以上均为用 2to3.py 转换后的文件。

**Comment by xmcp** [comment]
那就打开文件的参数改成`wb`

**Comment by ixiusama** [comment]
> 那就打开文件的参数改成wb 
这个是什么意思能否详细解释一下。

**Comment by ixiusama** [comment]
> 那就打开文件的参数改成`wb`

相同报错。
 修改为
`   f.write(r.text.encode('utf-8').decode('utf-8'))`
报错
`UnicodeEncodeError: 'gbk' codec can't encode character '\u2006' in position 43797: illegal multibyte sequence`

 修改为
    f.write(r.text.decode('utf-8'))
报错
`AttributeError: 'str' object has no attribute 'decode'`

 修改为
`    f.write(r.text.encode('utf-8'))`
报错
`TypeError: write() argument must be str, not bytes`

**Comment by ixiusama** [comment]
算了，我还是学习一下python 3 以后再说吧。现在先用着python 2.7 的版本吧。

**Comment by liuyang007** [comment]
用r.content啊

**Comment by liuyang007** [comment]
用r.content啊
