### ISSUE TITLE
如何获取已发送信息的ToUserID

### ISSUE THREAD

**Issue by weaming** [liuwons/wxBot#6]
RT

**Comment by liuwons** [comment]
已经发送的信息无非两种情况：别人发给自己的，那么可以直接用 `self.user['UserName']` ，要么是自己发给别人的消息，那么自己肯定是知道的。

**Comment by weaming** [comment]
@liuwons 我找了老半天。。

**Comment by liuwons** [comment]
@weaming 没时间完善文档。。。

**Comment by weaming** [comment]
@liuwons 群聊里面怎么开启呢（我还没看文档。。

**Comment by liuwons** [comment]
@weaming 只回复在群里@自己的消息
