### ISSUE TITLE
您好，请问你有语音发送的接口么

### ISSUE THREAD

**Issue by fendoude007** [liuwons/wxBot#60]
我们要做一个多群直播，其余的基本都按照您的代码或者研究成果用nodejs实现了，但是没有语音发送的接口，从webwx保存的源码里也没有这个接口，如果您知道的话方便告诉我么，有实现的方式或者可以知道提示的链接也可以，谢谢

**Comment by liuwons** [comment]
@fendoude007 Web微信没有发送语音的功能，所以我这也没有发送语音的接口。

**Comment by fendoude007** [comment]
那请问您了解一些 好多做微信群直播的是怎么实现语音转播的么？是通过APP的接口还是什么其他的……

**Comment by liuwons** [comment]
@fendoude007 应该是通过APP的接口实现的，可能是Android微信客户端。

**Comment by fendoude007** [comment]
OK 谢谢了
