### ISSUE TITLE
Python没有函数重载,请问这句是谁写的????

### ISSUE THREAD

**Issue by liuyang007** [liuwons/wxBot#61]
def get_group_member_info(self, uid):
        if uid in self.account_info['group_member']:
            return self.account_info['group_member'][uid]
        else:
            return None

    def get_group_member_info(self, uid, gid):
        if gid not in self.group_members:
            return None
        for member in self.group_members[gid]:
            if member['UserName'] == uid:
                return {'type': 'group_member', 'info': member}
        return None
@liuwons

**Comment by liuwons** [comment]
@liuyang007 忘记没有重载了，谢谢提醒~
