### ISSUE TITLE
无法获取群聊内每位成员的信息

### ISSUE THREAD

**Issue by mqbing** [liuwons/wxBot#80]
群聊内有信息，机器人在启动时无法获取， 导致群内@后，无法获取用户信息，返回unknow 。

**Comment by liuwons** [comment]
群已经保存到联系人了吗？
如果没有保存，是获取不到群成员的。

**Comment by fanzai1hao** [comment]
你在群里的昵称必须是你的微信昵称

**Comment by bombless** [comment]
是说群名称和微信名一致的时候才能正确返回`to 名字`么

**Comment by mqbing** [comment]
已经找到问题了，非常感谢

**Comment by CrytisMT** [comment]
怎么解决的呢
