### ISSUE TITLE
群消息得不到发送都的昵称

### ISSUE THREAD

**Issue by featheraaa** [liuwons/wxBot#88]
def handle_msg_all(self, msg):
        if msg['msg_type_id'] == 3  and msg['content']['type'] == 6：
            print msg['content']['user']['name']

结果总是unknow

**Comment by liuwons** [comment]
群是否已经保存到通讯录？

**Comment by featheraaa** [comment]
@liuwons  没有的，是不是没保存就一定得不到？

**Comment by xmcp** [comment]
@featheraaa 问题与 #67 #80 类似
