### ISSUE TITLE
能否增加一个 分享图文 链接 的功能

### ISSUE THREAD

**Issue by sixian67** [liuwons/wxBot#89]
可发送 分享图文 到指定uid

**Comment by baicaiaichibaicai** [comment]
想问一下退出程序时能否将信息保存起来，下次运行程序时先加载一下这些信息，然后试着去获取消息，这样子可以免去频繁扫码？

**Comment by xmcp** [comment]
@baicaiaichibaicai 退出之后sessoin会过期，免不了重新扫码

**Comment by intothephone** [comment]
Web微信为什么不添加此功能？应该是很简单的啊
