### ISSUE TITLE
如何进行开发（就是保存后热更新）或者终止重新运行时不用重新扫码登录？另外如何判断机器人被 at 的情况？

### ISSUE THREAD

**Issue by imWildCat** [liuwons/wxBot#90]

**Comment by liuwons** [comment]
- 热更新的话可以考虑将所有的回复内容都放到一个指定的位置(文件、数据库或者网络上)而不是程序中，推荐使用 **json** 文件。
- **at** 可以参考 ```bot.py``` 中：

  ```python
  is_at_me = False
  for detail in msg['content']['detail']:
      if detail['type'] == 'at':
          for k in my_names:
              if my_names[k] and my_names[k] == detail['value']:
                  is_at_me = True
                  break
  if is_at_me:
  ```

- 终止运行后扫码是必要的，因为微信服务器端的 **session** 会过期，就像每次你登录 Web 微信都需要重新扫码一样。

**Comment by liuwons** [comment]
@imWildCat

**Comment by baicaiaichibaicai** [comment]
@liuyang007  想问下你的cookie保存是怎么做的，有示例代码吗？

**Comment by baicaiaichibaicai** [comment]
@liuyang007  你好，我保存和加载cookies的示例代码是
保存：'Cookies' : requests.utils.dict_from_cookiejar(self.Session.cookies)  #保存成字典
加载：self.Session.cookies = requests.utils.cookiejar_from_dict(info['Cookies'])

登陆的时候依然失败

**Comment by vivre90** [comment]
试试 cPickle 库，直接保存  到本地文件即可

**Comment by taskj** [comment]
请问大家在获取新消息的时候，需要提交那个取反时间戳的rr的参数，用~int(time.time())，得到的值是负数，但是用firebug查看，这个参数是正数，有谁遇到个这个问题吗？求解答
