### ISSUE TITLE
消息延迟一秒发送

### ISSUE THREAD

**Issue by tsai1993** [liuwons/wxBot#93]
消息秒回感觉并不好……能适当延迟一两秒更好。不然两个机器人对聊太疯狂了。

**Comment by xmcp** [comment]
自己加延时啊

**Comment by vivre90** [comment]
import time
import random

#随机延迟0-10秒
time.sleep(random.randint(0,10)))

**Comment by ylot0** [comment]
加在哪里呢？

**Comment by xmcp** [comment]
@ylot0 加在回复消息之前呀

**Comment by ylot0** [comment]
@xmcp 呵呵，你还是告诉我加在bot.py的第几行里吧。拜托！谢谢！呵呵！！！

**Comment by xmcp** [comment]
呵呵，在每处`send_msg_by_uid`调用前面都加上。

或者干脆重写send_msg_by_uid方法：
```python
def send_msg_by_uid(*args, **kwargs):
    time.sleep(1)
    super().send_msg_by_uid(*args,**kwargs)
```

没关系！不客气！呵呵！！！
